### ISSUE TITLE
Delete button sometimes not reacting

### ISSUE THREAD

**Issue by friedger** [novoda/download-manager#102]
In demo-extend:
Delete buttons seems to not respond to clicks sometimes

Nexus 4, Android 5.1

**Comment by xrigau** [comment]
this can be fixed by using `getDownloadsWithoutProgress` introduced here https://github.com/novoda/download-manager/pull/97

and getting rid of the usage of QueryTimestamp https://github.com/novoda/download-manager/blob/master/demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/delete/DeleteActivity.java#L38

**Comment by xrigau** [comment]
I believe was fixed in #56
