### ISSUE TITLE
download fails if app removed from recent list

### ISSUE THREAD

**Issue by Hackmodford** [novoda/download-manager#209]
I have setup my app to only allow 1 concurrent download.
If I start a download and wait for it to have progress, then remove the app from the recent list I get some strange behavior.

The notification gets removed a few seconds after doing this. Which to me looks like the download gets paused/stopped. Then the notification comes back like it is trying to resume the download, but it fails to resume the download. Then it proceeds to begin downloading the next file in the queue.

Is this expected behavior?

**Comment by stefanhoth** [comment]
Thanks for using download manager. To your questions:

1. To my knowledge, removing an app from recents kills the process and with doing so the download in progress. So far I assume expected behaviour.

2. Usually download manager would be able to resume the download. If it can't the likely answer is that the server doesn't support resuming, either because it doesn't allow to jump ahead or because your session expires after one download. Could this be the case here?

Pinging @ouchadam for detailed answers with actual knowledge.

**Comment by ouchadam** [comment]
like @stefanhoth mentioned, the killing of the process also killing the download is expected. This library takes the stock shared system service `DownloadManager` and reimplements it as a app process (I believe the original intention was to allow access to the private app storage).

As for the resuming, are you able to pause/resume under normal conditions? 

It's likely ending the process early puts the database in an inconsistent state.

also worth noting there's an effort to rewrite this library with the same functionality from scratch dropping all the inherited AOSP code.

https://github.com/novoda/download-manager/tree/v2

**Comment by tasomaniac** [comment]
If we use an Android `Service` with posting `Notification` using `startForeground();` method, the process shouldn't be killed when user swipes the app from Recents. 

You can test it in music apps, when you swipe the app, the notification + music playback should continue. 

We can potentially use the same mechanism to do that.

**Comment by Hackmodford** [comment]
Still does this in the latest version. I like @tasomaniac's service idea.

**Comment by Hackmodford** [comment]
Pull request #237 fixes this issue for me.
