### ISSUE TITLE
Pull the latest changes from AOSP

### ISSUE THREAD

**Issue by xrigau** [novoda/download-manager#22]
It'd be good to pull changes/improvements/bugfixes (if any) from the AOSP from Lollipop or even Android M

**Comment by ronocod** [comment]
2 issues we've found with this:

* There's already been so many changes from the AOSP code that merging in newer versions will be very time-consuming.
* AOSP has moved to using JobScheduler for downloads cleanup since last June, so we'll have to remove any AOSP code that's not compatible with API 14.

**Comment by ronocod** [comment]
Also if we move away from keeping the code AOSP-based then we can start refactoring a lot more as we wouldn't care about staying close to the original code.

**Comment by blundell** [comment]
yeah we don't want to pull changes. Only any perf improvements or bug fixes that we notice in the aosp issue list.
