### ISSUE TITLE
File not downloading in app's internal storage

### ISSUE THREAD

**Issue by sunwicked** [novoda/download-manager#463]
- Set up batch download
- Download location = Internal app's storage
- Download shows in progress then status changes to completed
But no file is present in the downloaded location.  

Looks related to #190

**Comment by MechaRyRy** [comment]
Hi @sunwicked is this issue with v1 or v2?

**Comment by sunwicked** [comment]
v2

**Comment by MechaRyRy** [comment]
@sunwicked would you be able to provide me with any source code so that I can help you out?

- Were you able to reproduce the issue with the demo?
- Do you have any example code, showing the `storage root` and `Batch.with` download locations. 
- Did you request the necessary permissions for writing to your desired location?

**Comment by sunwicked** [comment]
Hi
The error was on my part. Wrong path supplied at the time of creating and getting the file.
